### ISSUE TITLE
Potential systemd-boot problems

### ISSUE THREAD

**Issue by Frozen-Sherbet** [sugarykeytone/Manjaro_to_Arch_Linux#18]
I was reading through the script and there was a comment that said 
> Manjaro doesn't have an option to install systemd-boot, Right?

If you use Architect, the command line version of the installer systemd-boot is an option. How should this script be modified this to work without requiring I chroot back into the system to reconfigure it?

**Comment by sugarykeytone** [comment]
I'll use ` bootctl status | grep enabled` then.

**Comment by sugarykeytone** [comment]
Fixed at commit b56b84201fc1de6c87beda81d21412bffce13704 .

**Comment by Frozen-Sherbet** [comment]
Gracias
