### ISSUE TITLE
Fatal Script Error

### ISSUE THREAD

**Issue by LinuxSnapshot** [sugarykeytone/Manjaro_to_Arch_Linux#20]
Hello, I was testing this script with Manjaro KDE version in gnome-boxes. However, UEFI Firmware Settings and Arch Linux were not visible in GRUB during the restart process after all processes were completed. Only the Memory Test was shown.

**Comment by sugarykeytone** [comment]
What version did you use?

**Comment by LinuxSnapshot** [comment]
> What version did you use?

Manjaro to Arch Linux version: v5.0.2

Manjaro Linux version: Manjaro Linux (KDE Plasma) 21.1.6

**Comment by sugarykeytone** [comment]
looks like a grub settings issue. I'll check it.

**Comment by sugarykeytone** [comment]
I found the issue at the UEFI part. I'll fix it soon.

**Comment by sugarykeytone** [comment]
- [x] Testing on UEFI firmware.... succeeded.
 - [ ] Testing BIOS....
 
`[Autotest bot by Sugary Keytone]`

**Comment by sugarykeytone** [comment]
Both tests have succeeded on the git branch.
Closing issue.

`[Autotest bot by Sugary Keytone]`

**Comment by sugarykeytone** [comment]
Is your issue fixed now?

**Comment by LinuxSnapshot** [comment]
> Is your issue fixed now?

No, but installing EndeavourOS solved the problem.

**Comment by kske-igrshi** [comment]
Bare metal/QEMU/VirtualBox works, gnome-boxes won't work. It isn't a good virtualization platform.
